# registry: "gethue"
# tag: "latest"
registry: "localhost:32000"
tag: "registry"
hue:
  database:
    create: true
    engine: "postgresql_psycopg2"
    host: "hue-postgres"
    port: 5432
    user: "hue"
    password: "hue"
    name: "hue"
  interpreters: |
    [[[impala]]]
      name=Impala
      interface=hiveserver2
    [[[mysql]]]
      name = MySQL
      interface=sqlalchemy
      options='{"url": "mysql://hue:datasshue@romain2:3306/hue"}'
    [[[postgresql]]]
      name = postgresql
      interface=sqlalchemy
      options='{"url": "postgresql://hue:hue@hue-postgres:5432/hue"}'


  ini: |
    [desktop]
    app_blacklist=filebrowser,search,hbase,security,jobbrowser,metastore

    [[task_server]]
    enabled=true
    ## broker_url=amqp://guest:guest@127.0.0.1//
    broker_url=redis://redis:6379/0

    [impala]
    server_host=172.31.114.171

    [dashboard]
    is_enabled=false
    has_sql_enabled=false

    [notebook]
    show_notebooks=false

    [hadoop]
balancer:
  enabled: true
workers:
  enabled: true
  replicas: 1
scheduler:
  enabled: true
aws:
  accessKeyId: ""
  secretAccessKey: ""
  region: "us-east-1"
ingress:
  create: false
  type: "traefik"
  loadBalancerIp: "127.0.0.1"
  domain: "127.0.0.1.nip.io"
