{{- if .Values.ingress.create -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-hue-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - demo2.gethue.com
    secretName: letsencrypt-prod
  rules:
  - host: demo2.gethue.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hue
          servicePort: 80
{{- end -}}
